### PR TITLE
feat: add filter to resource config

### PR DESCRIPTION
**Pull request by singhvikash11**

### CODE REVIEW

**Comment by mabdh** [comment]
@singhvikash11 can you please give more context on this? or link to the related issue if any?

**Comment by singhvikash11** [comment]
@mabdh @rahmatrhd can you please approve this, it is used in pr github.com/odpf/guardian/pull/323

**Comment by singhvikash11** [comment]
@bsushmith can you please review and approve this

**Comment by bsushmith** [comment]
Need these changes for - https://github.com/odpf/guardian/issues/313

**Review by mabdh — APPROVED** [review]

**Pull request merged**
