### PR TITLE
feat(assets): add support to capture schema of nested columns.

### PR DESCRIPTION
**Pull request by anjali9791**
This helps in adding the schema for nested column in bigquery. 
Related to https://github.com/odpf/meteor/issues/462

### CODE REVIEW

**Comment by sudo-suhas** [comment]
@anjali9791 could you please share some relevant documentation on BigQuery that can help me understand the need for this feature?

**Comment by anjali9791** [comment]
> @anjali9791 could you please share some relevant documentation on BigQuery that can help me understand the need for this feature?

**Comment by anjali9791** [comment]
@sudo-suhas : Please refer this : https://cloud.google.com/bigquery/docs/nested-repeated

**Review by sudo-suhas — APPROVED** [review]
LGTM

**Pull request merged**
